import {
  Activity,
  Armchair,
  Award,
  Baby,
  BriefcaseMedical,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  Clock,
  FileImage,
  Heart,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  Quote,
  ShieldCheck,
  Smile,
  Sparkles,
  SquareParking,
  Star,
  Stethoscope,
  Syringe,
  UserCheck,
  Wallet,
  Wrench,
  X,
  ArrowRight,
} from 'lucide-react'

const ICON_MAP = {
  stethoscope: Stethoscope,
  shield: ShieldCheck,
  sparkle: Sparkles,
  sparkles: Sparkles,
  rootCanal: Activity,
  implant: Syringe,
  crown: Award,
  whitening: Smile,
  braces: Wrench,
  child: Baby,
  surgery: BriefcaseMedical,
  denture: Smile,
  gum: Heart,
  trust: UserCheck,
  wallet: Wallet,
  xray: FileImage,
  sterile: CheckCircle,
  chair: Armchair,
  parking: SquareParking,
  phone: Phone,
  mail: Mail,
  pin: MapPin,
  clock: Clock,
  check: Check,
  star: Star,
  whatsapp: MessageCircle,
  arrow: ArrowRight,
  chevron: ChevronDown,
  menu: Menu,
  close: X,
  calendar: Calendar,
  quote: Quote,
  tooth: Smile,
}

export default function Icon({ name, size = 24, strokeWidth = 1.7, className = '', labelStyle, ...props }) {
  const IconComponent = ICON_MAP[name] || Sparkles
  return <IconComponent size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" {...props} />
}